[hooks]
pre-commit = ["rustfmt **/*.rs", "cargo test"]
pre-push = [
    "cargo fmt --all -- --check",
    "rustfmt --check tests/**/*.rs",
    "cargo clippy -- -Dclippy::all -Dclippy::pedantic",
]

[logging]
verbose = true
