[package]
name = "sealed"
version = "0.1.0"
authors = ["José Duarte <jmg.duarte@campus.fct.unl.pt>"]
edition = "2018"

[lib]
proc-macro = true

[dev-dependencies]
trybuild = { version = "1.0", features = ["diff"] }

[dependencies]
syn = {version = "1.0", features = ["full", "parsing", "extra-traits"]}
quote = "1.0"
proc-macro2 = "1.0"